### ISSUE TITLE
Branding styles cannot override PatternFly styles with `:root` selector

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#787]
The following branding css doesn't override the PF global variables. The PF default styles always take precedence over the branding styles.

```css
.pf-c-login,
.pf-c-about-modal-box__hero {
  background-image: url("./background.png") !important;
  background-size: cover;
}
:root {
  --pf-global--primary-color--100: #B21054;
  --pf-global--primary-color--200: #B24E78;
  --pf-global--primary-color--light-100: #B24E78;
  --pf-global--primary-color--dark-100: #B21054;
  --pf-global--active-color--100: #B21054;
  --pf-global--active-color--200: #B24E78;
  --pf-global--active-color--300: #B24E78;
  --pf-global--active-color--400: #B24E78;
  --pf-global--link--Color: #B21054;
  --pf-global--link--Color--hover: #B24E78;
  --pf-v5-global--primary-color--100: #B21054;
  --pf-v5-global--primary-color--200: #B24E78;
  --pf-v5-global--link--Color: var(--pf-v5-global--danger-color--100);
}
```
